# Generated by Django 4.0.5 on 2022-06-29 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sis_vacuna', '0002_vacuna_rename_usuario_persona_vacunacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacuna',
            name='nombre_vacuna',
        ),
        migrations.AddField(
            model_name='vacuna',
            name='nombre',
            field=models.CharField(choices=[('pfizer', 'Pfizer'), ('Sinovac', 'Sinovac'), ('AstraZeneca', 'AstraZeneca'), ('CanSino', 'CanSino'), ('Janssen', 'Janssen'), ('SPUTNIK-V', 'SPUTNIK-V'), ('Moderna', 'Moderna'), ('Janssen', 'Janssen')], default='Moderna', max_length=30),
        ),
    ]
