# Generated by Django 4.0.5 on 2022-07-14 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_sis_vacuna', '0003_remove_vacuna_nombre_vacuna_vacuna_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='nombre_vacuna',
        ),
    ]
