# Generated by Django 4.0.5 on 2022-07-14 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sis_vacuna', '0004_remove_persona_nombre_vacuna'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacunacion',
            name='dosis',
            field=models.CharField(choices=[('1', 'Primera Docis'), ('2', 'Segunda Docis'), ('3', 'Tercera Docis'), ('4', 'Cuarta Docis')], default='primera_docis', max_length=30),
        ),
    ]
