# Generated by Django 4.0.5 on 2022-07-14 01:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app_sis_vacuna', '0005_alter_vacunacion_dosis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='fecha',
        ),
        migrations.AddField(
            model_name='vacunacion',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 14, 1, 33, 19, 253562, tzinfo=utc), verbose_name='date published'),
        ),
    ]
