# Generated by Django 4.0.5 on 2022-07-14 01:57

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app_sis_vacuna', '0006_remove_persona_fecha_vacunacion_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacunacion',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 14, 1, 57, 48, 182184, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.CreateModel(
            name='PaseDeMovilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(default=datetime.datetime(2022, 7, 14, 1, 57, 48, 183116, tzinfo=utc), verbose_name='date published')),
                ('fecha_termino', models.DateTimeField(default=datetime.datetime(2022, 7, 14, 1, 57, 48, 183148, tzinfo=utc), verbose_name='date published')),
                ('vacunatorio', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateTimeField(default=datetime.datetime(2022, 7, 14, 1, 57, 48, 183255, tzinfo=utc), verbose_name='date published')),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_sis_vacuna.persona')),
            ],
        ),
    ]
