# Generated by Django 4.0.5 on 2022-07-14 03:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app_sis_vacuna', '0007_alter_vacunacion_fecha_pasedemovilidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pasedemovilidad',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 14, 3, 24, 6, 967064, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='pasedemovilidad',
            name='fecha_inicio',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 14, 3, 24, 6, 966915, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='pasedemovilidad',
            name='fecha_termino',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 14, 3, 24, 6, 966948, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='vacuna',
            name='nombre',
            field=models.CharField(choices=[('Pfizer', 'Pfizer'), ('Sinovac', 'Sinovac'), ('AstraZeneca', 'AstraZeneca'), ('CanSino', 'CanSino'), ('Janssen', 'Janssen'), ('SPUTNIK-V', 'SPUTNIK-V'), ('Moderna', 'Moderna')], default='Moderna', max_length=30),
        ),
        migrations.AlterField(
            model_name='vacunacion',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 14, 3, 24, 6, 965951, tzinfo=utc), verbose_name='date published'),
        ),
    ]
